# Generated by Django 4.2.6 on 2023-12-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0003_alter_user_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='user_id',
        ),
        migrations.AddField(
            model_name='groups',
            name='description',
            field=models.CharField(default='trial'),
            preserve_default=False,
        ),
    ]
