# Generated by Django 4.2.6 on 2023-12-16 04:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0004_remove_groups_user_id_groups_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=ckeditor.fields.RichTextField(default='a;ewoifjaw'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='editor_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_group', to='docs_app.groups'),
        ),
        migrations.AlterField(
            model_name='document',
            name='moderator_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_group', to='docs_app.groups'),
        ),
        migrations.AlterField(
            model_name='document',
            name='viewer_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_group', to='docs_app.groups'),
        ),
    ]
