# Generated by Django 4.2.6 on 2023-12-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0005_remove_document_tag_id_document_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(),
        ),
    ]
