# Generated by Django 4.2.6 on 2023-12-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0006_alter_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
