# Generated by Django 4.2.6 on 2023-12-17 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0007_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groups',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='description',
            field=models.CharField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tags',
            name='doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='docs_app.document'),
        ),
    ]
