# Generated by Django 4.2.6 on 2023-12-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0008_groups_number_groups_user_id_tags_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
