# Generated by Django 4.2.6 on 2023-12-18 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0009_alter_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='editor_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='editor_group', to='docs_app.groups'),
        ),
        migrations.AlterField(
            model_name='document',
            name='moderator_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_group', to='docs_app.groups'),
        ),
        migrations.AlterField(
            model_name='document',
            name='viewer_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='viewer_group', to='docs_app.groups'),
        ),
    ]
