# Generated by Django 4.2.6 on 2024-01-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0010_alter_document_editor_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
    ]
