# Generated by Django 4.2.6 on 2024-01-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0011_alter_user_options_alter_user_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(null=True),
        ),
    ]
